version: '3'

services:
  mysql:
    image: mysql
    container_name: choose-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: choose
      MYSQL_USER: sf
      MYSQL_PASSWORD: zxc?
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
  mongodb:
    image: 'bitnami/mongodb:3.6.23'
    environment:
      MONGODB_INITIAL_PRIMARY_PORT_NUMBER: 27017
      MONGODB_DATABASE: choose
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: root
    ports:
      - "27017:27017"
