spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:mysql://localhost:3306/choose?serverTimezone=UTC}
    username: ${JDBC_DATABASE_USERNAME:choose}
    password: ${JDBC_DATABASE_PASSWORD:choosechoosechoose}
  dbcp2:
    max-wait-millis: 30000
    validation-query: "SELECT 1"
    validation-query-timeout: 30
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      database: ${MONGO_DATABASE:choose}
      username: ${MONGO_USERNAME:choose}
      password: ${MONGO_PASSWORD:choose}
      authentication-database: choose
management:
  endpoint:
    health:
      probes:
        enabled: true
sendgrid:
  token: ${SENDGRID_TOKEN}
